# add stages here 
stages:
  prepare_data:
    cmd: python src/stage_01_prepare.py -c config/config.yaml -p params.yaml
    deps:
      - src/stage_01_prepare.py
      - data/data.xml
      - src/utils/all_utils.py
      - src/utils/data_management.py
      - config/config.yaml

    params:
      - prepare.seed
      - prepare.split

    outs:
      - artifacts\prepared\train.tsv
      - artifacts\prepared\test.tsv
  
  featurize:
    cmd: python src/stage_02_featurization.py -c config/config.yaml -p params.yaml
    deps:
      - src/stage_02_featurization.py
      - artifacts\prepared\test.tsv
      - artifacts\prepared\train.tsv
      - src/utils/all_utils.py
      - src\utils\featurize.py
      - config/config.yaml
    params:
      - featurize.ngrams
      - featurize.max_features
    outs:
      - artifacts\features\train.pkl
      - artifacts\features\test.pkl
  
  train:
    cmd: python src/stage_03_training.py -c config/config.yaml -p params.yaml
    deps:
      - src/stage_03_training.py
      - artifacts\prepared\train.tsv
      - src/utils/all_utils.py
      - config/config.yaml
    params:
      - train.seed
      - train.n_est
      - train.min_split
    outs:
      - artifacts\model\model.pkl

  

